on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check.yaml

jobs:
  R-CMD-check:
    uses: Public-Health-Scotland/workflows/.github/workflows/phs_R-CMD-check.yaml@main
    permissions: read-all
    secrets: inherit
